
devMode: true
user:    single_user  # TASK: remove (currently single user)

defaultSettings:      # see also users > settings.yml

  layout:

    useCoffeeCounter:  true
    useFillupsCounter: true

  foods:

    defaultAmounts:
      
      pack:   ["1/4", "1/3", "1"]
      pieces: [1, 2, 3]
