
devMode:   true         # show new ui elems that are in dev
tryDesign: false        # try new UI (see controller.php)

user:      single_user

substances:             # TASK: maybe move in nutrients
                        # TASK: rename
  gluten:  ['weizen']
  lactose: ['milch']

highIntake:             # TASK: maybe move in nutrients

  fat: 100

defaultSettings:        # see also users > settings.yml

  currency: "€"

  layout:

    useCoffeeCounter:  true
    useFillupsCounter: true

  foods:

    defaultAmounts:
      
      pack:   ["1/4", "1/3", "1"]
      pieces: [1, 2, 3]
