
devMode:     true         # show new ui elems that are in dev
tryDesign:   false        # try new UI (see controller.php)
special:     true         # show waj only functions (var-buy and similar)

defaultUser: "JaneDoe@example.com-24080101000000"

substances:                 # TASK: maybe move in nutrients
                            # TASK: rename
  gluten:  ['weizen']
  lactose: ['milch']

highIntake:                 # TASK: maybe move in nutrients

  fat: 100

defaultSettings:            # see also users > settings.yml

  currency:       "EUR"     # currently EUR or USD
  currencySymbol: "&euro;"  # icon is a little nicer
  currencyIcon:   "bi-currency-euro"  # bi-currency-dollar
  cheap:          0.40      # per 100 g or ml
  expensive:      0.80

  foods:

    defaultAmounts:
      
      pack:   ["1/4", "1/3", "1"]
      pieces: [1, 2, 3]
