
# see also users > settings.yml

devMode: true

user:  single_user  # TASK: remove (currently single user)
foods:              # TASK: move settings

  defaultAmounts:
    
    pack:
      
      - "1/4"
      - "1/3"
      - "1/2"
      - "1"

    pieces:

      - 1
      - 2
      - 3
