
devMode: true
user:    single_user  # TASK: remove (currently single user)

# default settings
# see also users > settings.yml

foods:

  defaultAmounts:
    
    pack:   ["1/4", "1/3", "1/2", "1"]
    pieces: [1, 2, 3]
